In [1]:
import torch

In [3]:
a = torch.tensor([[1,2,3,4,5], [1,1,1,1,1]])

In [4]:
b = 2*a

In [5]:
a + b

tensor([[ 3,  6,  9, 12, 15],
        [ 3,  3,  3,  3,  3]])

In [6]:
b

tensor([[ 2,  4,  6,  8, 10],
        [ 2,  2,  2,  2,  2]])

In [7]:
a.shape

torch.Size([2, 5])

In [12]:
c = torch.tensor([2, 3])
c.shape

torch.Size([2])

In [14]:
torch.div(a, c[:, None])

tensor([[0.5000, 1.0000, 1.5000, 2.0000, 2.5000],
        [0.3333, 0.3333, 0.3333, 0.3333, 0.3333]])

In [15]:
c[:, None]

tensor([[2],
        [3]])

In [17]:
(b > 2).float()

tensor([[0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.]])